In [100]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [118]:
import polars as pl
import polars.selectors as cs
from datetime import datetime
from src.commons import data_loader, data_cleanser

## -- Configuración profesional de visualización en Polars

In [119]:
# Configuración profesional de visualización en Polars

# Limit the maximum rows and columns shown in prints
pl.Config.set_tbl_rows(10)
pl.Config.set_tbl_cols(15)

pl.Config.set_fmt_str_lengths(300)   # Trunca textos largos a 15 caracteres para no romper la línea
pl.Config.set_tbl_width_chars(150)  # Ajusta el ancho total de la tabla en pantalla

polars.config.Config

## -- Constants Variables for File names

In [129]:
UTILITY_PROVIDER_FILE = "utility_provider"
SUBSTATION_FILE = "substation"
CONSUMER_FILE = "consumer"
AMI_HEAD_END_FILE = "ami_head_end"
DATA_MGMT_SYSTEM_FILE = "data_mgmt_system"
DISTRIBUTION_NETWORK_FILE = "distribution_network"
DISTRIBUTION_TRANSFORMER_FILE = "distribution_transformer"
ENERGY_STORAGE_FILE = "energy_storage"
POWER_PLANT_FILE = "power_plants"
POWER_TRANSFORMER_FILE = "power_transformer"
RENEWABLE_SOURCE_FILE = "renewable_source"
SCADA_DMS_FILE = "scada_dms"
SMART_METERS_FILE = "smart_meters"

## -- Data Ingestion from CSV files

In [121]:
df_utility_provider = data_loader.ingest_data(UTILITY_PROVIDER_FILE)

/workspace/data/1_rawdata/utility_provider.csv
/workspace/data/2_bronze/utility_provider.parquet

In [138]:
df_substation = data_loader.ingest_data(SUBSTATION_FILE)

In [143]:
df_consumer = data_loader.ingest_data(CONSUMER_FILE)

In [145]:
df_ami_head_end = data_loader.ingest_data(AMI_HEAD_END_FILE)

In [148]:
df_data_mgmt_system = data_loader.ingest_data(DATA_MGMT_SYSTEM_FILE)

In [150]:
df_distribution_network = data_loader.ingest_data(DISTRIBUTION_NETWORK_FILE)

In [154]:
df_distribution_transformer = data_loader.ingest_data(DISTRIBUTION_TRANSFORMER_FILE)

In [152]:
df_energy_storage = data_loader.ingest_data(ENERGY_STORAGE_FILE)

In [156]:
df_power_plants =  data_loader.ingest_data(POWER_PLANT_FILE)

In [158]:
df_power_transformer = data_loader.ingest_data(POWER_TRANSFORMER_FILE)

In [160]:
df_renewable_source = data_loader.ingest_data(RENEWABLE_SOURCE_FILE)

In [162]:
df_scada_dms = data_loader.ingest_data(SCADA_DMS_FILE)

In [165]:
df_smart_meters = data_loader.ingest_data(SMART_METERS_FILE)

## -- DATA CLEANSING & HARMONIZATION - UTILITY PROVIDER

In [137]:
data_cleanser.clean_data(df_utility_provider, UTILITY_PROVIDER_FILE, "provider_id", None)

shape: (5, 5)
┌─────────────┬─────────────────────────┬─────────┬────────────────────────────┬──────────────────────┐
│ provider_id ┆ name                    ┆ region  ┆ ingested_at                ┆ ingested_from        │
│ ---         ┆ ---                     ┆ ---     ┆ ---                        ┆ ---                  │
│ str         ┆ str                     ┆ str     ┆ datetime[μs]               ┆ str                  │
╞═════════════╪═════════════════════════╪═════════╪════════════════════════════╪══════════════════════╡
│ UP-001      ┆ Andes Power Co          ┆ North   ┆ 2026-09-04 05:34:59.076883 ┆ utility_provider.csv │
│ UP-002      ┆ Pacifica Energy         ┆ South   ┆ 2026-09-04 05:34:59.076883 ┆ utility_provider.csv │
│ UP-003      ┆ Northern Grid Utilities ┆ East    ┆ 2026-09-04 05:34:59.076883 ┆ utility_provider.csv │
│ UP-004      ┆ Meridian Electric       ┆ West    ┆ 2026-09-04 05:34:59.076883 ┆ utility_provider.csv │
│ UP-005      ┆ Southern Cross Power    ┆ Central ┆ 2026-09-04 05:34:59.076883 ┆ utility_provider.csv │
└─────────────┴─────────────────────────┴─────────┴────────────────────────────┴──────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - SUBSTATION

In [140]:
data_cleanser.clean_data(df_substation, SUBSTATION_FILE, "substation_id", ['voltage_kv'])

shape: (500, 9)
┌───────────────┬─────────────────┬──────────────┬────────────┬──────────────────┬───────────┬──────────┬─────────────────┬────────────────┐
│ substation_id ┆ substation_type ┆ location     ┆ voltage_kv ┆ source_type      ┆ source_id ┆ scada_id ┆ ingested_at     ┆ ingested_from  │
│ ---           ┆ ---             ┆ ---          ┆ ---        ┆ ---              ┆ ---       ┆ ---      ┆ ---             ┆ ---            │
│ str           ┆ str             ┆ str          ┆ f64        ┆ str              ┆ str       ┆ str      ┆ datetime[μs]    ┆ str            │
╞═══════════════╪═════════════════╪══════════════╪════════════╪══════════════════╪═══════════╪══════════╪═════════════════╪════════════════╡
│ SUB-0001      ┆ Step-down       ┆ District 80  ┆ 138.0      ┆ POWER_PLANT      ┆ PP-0004   ┆ SCD-003  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0002      ┆ Step-down       ┆ District 119 ┆ 138.0      ┆ RENEWABLE_SOURCE ┆ RS-0024   ┆ SCD-001  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0003      ┆ Distribution    ┆ District 3   ┆ 500.0      ┆ ENERGY_STORAGE   ┆ ES-0017   ┆ SCD-001  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0004      ┆ Transmission    ┆ District 80  ┆ 230.0      ┆ ENERGY_STORAGE   ┆ ES-0009   ┆ SCD-002  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0005      ┆ Step-up         ┆ District 17  ┆ 69.0       ┆ ENERGY_STORAGE   ┆ ES-0005   ┆ SCD-008  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ …             ┆ …               ┆ …            ┆ …          ┆ …                ┆ …         ┆ …        ┆ …               ┆ …              │
│ SUB-0496      ┆ Distribution    ┆ District 102 ┆ 138.0      ┆ POWER_PLANT      ┆ PP-0012   ┆ SCD-005  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0497      ┆ Step-down       ┆ District 108 ┆ 13.8       ┆ POWER_PLANT      ┆ PP-0014   ┆ SCD-004  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0498      ┆ Step-down       ┆ District 36  ┆ 500.0      ┆ ENERGY_STORAGE   ┆ ES-0013   ┆ SCD-001  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0499      ┆ Transmission    ┆ District 85  ┆ 230.0      ┆ POWER_PLANT      ┆ PP-0006   ┆ SCD-005  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
│ SUB-0500      ┆ Transmission    ┆ District 71  ┆ 230.0      ┆ ENERGY_STORAGE   ┆ ES-0008   ┆ SCD-009  ┆ 2026-09-04      ┆ substation.csv │
│               ┆                 ┆              ┆            ┆                  ┆           ┆          ┆ 06:07:11.896318 ┆                │
└───────────────┴─────────────────┴──────────────┴────────────┴──────────────────┴───────────┴──────────┴─────────────────┴────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - CONSUMER

In [144]:
data_cleanser.clean_data(df_consumer, CONSUMER_FILE, "consumer_id", None)

shape: (13_500_000, 5)
┌──────────────┬──────────────┬────────────────────────────┬────────────────────────────┬───────────────┐
│ consumer_id  ┆ account_type ┆ address                    ┆ ingested_at                ┆ ingested_from │
│ ---          ┆ ---          ┆ ---                        ┆ ---                        ┆ ---           │
│ str          ┆ str          ┆ str                        ┆ datetime[μs]               ┆ str           │
╞══════════════╪══════════════╪════════════════════════════╪════════════════════════════╪═══════════════╡
│ CON-00000001 ┆ Residential  ┆ 6818 Hill St, Stonebridge  ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-00000002 ┆ Commercial   ┆ 399 Lake Dr, Clearwater    ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-00000003 ┆ Residential  ┆ 6673 Hill St, Lakeside     ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-00000004 ┆ Residential  ┆ 5824 Main St, Fairview     ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-00000005 ┆ Residential  ┆ 2225 Elm St, Meadowbrook   ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ …            ┆ …            ┆ …                          ┆ …                          ┆ …             │
│ CON-13499996 ┆ Residential  ┆ 7457 Main St, Clearwater   ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-13499997 ┆ Residential  ┆ 4440 River Rd, Greenfield  ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-13499998 ┆ Residential  ┆ 5224 Elm St, Brookhaven    ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-13499999 ┆ Residential  ┆ 2434 Bridge Rd, Greenfield ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
│ CON-13500000 ┆ Residential  ┆ 6327 Park Ave, Lakeside    ┆ 2026-09-04 06:10:01.571315 ┆ consumer.csv  │
└──────────────┴──────────────┴────────────────────────────┴────────────────────────────┴───────────────┘

## -- DATA CLEANSING & HARMONIZATION   - AMI HEAD END

In [147]:
data_cleanser.clean_data(df_ami_head_end, AMI_HEAD_END_FILE, "hes_id", None)

shape: (200, 6)
┌─────────┬──────────────┬───────────────┬───────────────┬────────────────────────────┬──────────────────┐
│ hes_id  ┆ network_type ┆ coverage_area ┆ dms_system_id ┆ ingested_at                ┆ ingested_from    │
│ ---     ┆ ---          ┆ ---           ┆ ---           ┆ ---                        ┆ ---              │
│ str     ┆ str          ┆ str           ┆ str           ┆ datetime[μs]               ┆ str              │
╞═════════╪══════════════╪═══════════════╪═══════════════╪════════════════════════════╪══════════════════╡
│ HES-001 ┆ RF-Mesh      ┆ Zone 71       ┆ DMS-004       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-002 ┆ RF-Mesh      ┆ Zone 55       ┆ DMS-003       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-003 ┆ Cellular     ┆ Zone 48       ┆ DMS-004       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-004 ┆ RF-Mesh      ┆ Zone 17       ┆ DMS-002       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-005 ┆ Cellular     ┆ Zone 40       ┆ DMS-004       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ …       ┆ …            ┆ …             ┆ …             ┆ …                          ┆ …                │
│ HES-196 ┆ Fiber        ┆ Zone 51       ┆ DMS-001       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-197 ┆ Fiber        ┆ Zone 35       ┆ DMS-001       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-198 ┆ Cellular     ┆ Zone 13       ┆ DMS-004       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-199 ┆ PLC          ┆ Zone 17       ┆ DMS-001       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
│ HES-200 ┆ RF-Mesh      ┆ Zone 68       ┆ DMS-004       ┆ 2026-09-04 06:12:02.310128 ┆ ami_head_end.csv │
└─────────┴──────────────┴───────────────┴───────────────┴────────────────────────────┴──────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - DATA MANAGEMENT SYSTEM

In [149]:
data_cleanser.clean_data(df_data_mgmt_system, DATA_MGMT_SYSTEM_FILE, "system_id", None)

shape: (5, 6)
┌───────────┬─────────────┬────────────────┬──────────────────┬────────────────────────────┬──────────────────────┐
│ system_id ┆ provider_id ┆ storage_type   ┆ analytics_engine ┆ ingested_at                ┆ ingested_from        │
│ ---       ┆ ---         ┆ ---            ┆ ---              ┆ ---                        ┆ ---                  │
│ str       ┆ str         ┆ str            ┆ str              ┆ datetime[μs]               ┆ str                  │
╞═══════════╪═════════════╪════════════════╪══════════════════╪════════════════════════════╪══════════════════════╡
│ DMS-001   ┆ UP-005      ┆ Data Lake      ┆ DuckDB           ┆ 2026-09-04 06:13:52.592239 ┆ data_mgmt_system.csv │
│ DMS-002   ┆ UP-002      ┆ Data Lake      ┆ Spark            ┆ 2026-09-04 06:13:52.592239 ┆ data_mgmt_system.csv │
│ DMS-003   ┆ UP-004      ┆ Data Warehouse ┆ Presto           ┆ 2026-09-04 06:13:52.592239 ┆ data_mgmt_system.csv │
│ DMS-004   ┆ UP-001      ┆ Hybrid         ┆ Presto           ┆ 2026-09-04 06:13:52.592239 ┆ data_mgmt_system.csv │
│ DMS-005   ┆ UP-003      ┆ Data Lake      ┆ Presto           ┆ 2026-09-04 06:13:52.592239 ┆ data_mgmt_system.csv │
└───────────┴─────────────┴────────────────┴──────────────────┴────────────────────────────┴──────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - DISTRIBUTION NETWORK

In [151]:
data_cleanser.clean_data(df_distribution_network, DISTRIBUTION_NETWORK_FILE, "network_id", None)

shape: (2_000, 6)
┌────────────┬───────────────┬─────────────┬──────────┬────────────────────────────┬──────────────────────────┐
│ network_id ┆ substation_id ┆ feeder_type ┆ scada_id ┆ ingested_at                ┆ ingested_from            │
│ ---        ┆ ---           ┆ ---         ┆ ---      ┆ ---                        ┆ ---                      │
│ str        ┆ str           ┆ str         ┆ str      ┆ datetime[μs]               ┆ str                      │
╞════════════╪═══════════════╪═════════════╪══════════╪════════════════════════════╪══════════════════════════╡
│ DN-00001   ┆ SUB-0362      ┆ Mixed       ┆ SCD-006  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-00002   ┆ SUB-0051      ┆ Overhead    ┆ SCD-009  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-00003   ┆ SUB-0395      ┆ Underground ┆ SCD-009  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-00004   ┆ SUB-0330      ┆ Underground ┆ SCD-003  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-00005   ┆ SUB-0499      ┆ Underground ┆ SCD-002  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ …          ┆ …             ┆ …           ┆ …        ┆ …                          ┆ …                        │
│ DN-01996   ┆ SUB-0460      ┆ Underground ┆ SCD-010  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-01997   ┆ SUB-0238      ┆ Overhead    ┆ SCD-002  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-01998   ┆ SUB-0188      ┆ Overhead    ┆ SCD-003  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-01999   ┆ SUB-0186      ┆ Mixed       ┆ SCD-005  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
│ DN-02000   ┆ SUB-0438      ┆ Overhead    ┆ SCD-007  ┆ 2026-09-04 06:16:26.394673 ┆ distribution_network.csv │
└────────────┴───────────────┴─────────────┴──────────┴────────────────────────────┴──────────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - DISTRIBUTION TRANSFORMER

In [27]:
print(df_distribution_transformer.head(5))

shape: (5, 3)
┌────────────────┬────────────┬───────────┐
│ Transformer ID ┆ Network ID ┆ Rated KVA │
│ ---            ┆ ---        ┆ ---       │
│ str            ┆ str        ┆ i64       │
╞════════════════╪════════════╪═══════════╡
│ DXF-000001     ┆ DN-00261   ┆ 75        │
│ DXF-000002     ┆ DN-00424   ┆ 75        │
│ DXF-000003     ┆ DN-00844   ┆ 50        │
│ DXF-000004     ┆ DN-00037   ┆ 50        │
│ DXF-000005     ┆ DN-00791   ┆ 250       │
└────────────────┴────────────┴───────────┘

In [155]:
data_cleanser.clean_data(df_distribution_transformer, DISTRIBUTION_TRANSFORMER_FILE, "transformer_id", ['rated_kva'])

shape: (150_000, 5)
┌────────────────┬────────────┬───────────┬────────────────────────────┬──────────────────────────────┐
│ transformer_id ┆ network_id ┆ rated_kva ┆ ingested_at                ┆ ingested_from                │
│ ---            ┆ ---        ┆ ---       ┆ ---                        ┆ ---                          │
│ str            ┆ str        ┆ i64       ┆ datetime[μs]               ┆ str                          │
╞════════════════╪════════════╪═══════════╪════════════════════════════╪══════════════════════════════╡
│ DXF-000001     ┆ DN-00261   ┆ 75        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-000002     ┆ DN-00424   ┆ 75        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-000003     ┆ DN-00844   ┆ 50        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-000004     ┆ DN-00037   ┆ 50        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-000005     ┆ DN-00791   ┆ 250       ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ …              ┆ …          ┆ …         ┆ …                          ┆ …                            │
│ DXF-149996     ┆ DN-00522   ┆ 75        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-149997     ┆ DN-01707   ┆ 250       ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-149998     ┆ DN-00048   ┆ 25        ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-149999     ┆ DN-01842   ┆ 167       ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
│ DXF-150000     ┆ DN-01942   ┆ 500       ┆ 2026-09-04 06:19:50.939155 ┆ distribution_transformer.csv │
└────────────────┴────────────┴───────────┴────────────────────────────┴──────────────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - ENERGY STORAGE

In [153]:
data_cleanser.clean_data(df_energy_storage, ENERGY_STORAGE_FILE, "storage_id", ['capacity_kwh'])

shape: (20, 5)
┌────────────┬──────────────┬──────────────┬────────────────────────────┬────────────────────┐
│ storage_id ┆ type         ┆ capacity_kwh ┆ ingested_at                ┆ ingested_from      │
│ ---        ┆ ---          ┆ ---          ┆ ---                        ┆ ---                │
│ str        ┆ str          ┆ f64          ┆ datetime[μs]               ┆ str                │
╞════════════╪══════════════╪══════════════╪════════════════════════════╪════════════════════╡
│ ES-0001    ┆ Lithium-Ion  ┆ 58825.7      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0002    ┆ Flow Battery ┆ 65334.8      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0003    ┆ Pumped Hydro ┆ 9360.0       ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0004    ┆ Lithium-Ion  ┆ 42164.9      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0005    ┆ Pumped Hydro ┆ 5119.8       ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ …          ┆ …            ┆ …            ┆ …                          ┆ …                  │
│ ES-0016    ┆ Pumped Hydro ┆ 3257.6       ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0017    ┆ Pumped Hydro ┆ 95897.4      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0018    ┆ Flow Battery ┆ 48748.0      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0019    ┆ Flow Battery ┆ 78490.8      ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
│ ES-0020    ┆ Pumped Hydro ┆ 9190.3       ┆ 2026-09-04 06:17:49.671603 ┆ energy_storage.csv │
└────────────┴──────────────┴──────────────┴────────────────────────────┴────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - POWER PLANTS

In [157]:
data_cleanser.clean_data(df_power_plants, POWER_PLANT_FILE, "plant_id", ['capacity_mw'])

shape: (25, 6)
┌──────────┬─────────────┬────────┬─────────────┬────────────────────────────┬──────────────────┐
│ plant_id ┆ provider_id ┆ type   ┆ capacity_mw ┆ ingested_at                ┆ ingested_from    │
│ ---      ┆ ---         ┆ ---    ┆ ---         ┆ ---                        ┆ ---              │
│ str      ┆ str         ┆ str    ┆ f64         ┆ datetime[μs]               ┆ str              │
╞══════════╪═════════════╪════════╪═════════════╪════════════════════════════╪══════════════════╡
│ PP-0001  ┆ UP-001      ┆ Coal   ┆ 332.2       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0002  ┆ UP-004      ┆ Gas    ┆ 726.7       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0003  ┆ UP-004      ┆ Diesel ┆ 113.5       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0004  ┆ UP-003      ┆ Gas    ┆ 273.7       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0005  ┆ UP-003      ┆ Gas    ┆ 1040.4      ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ …        ┆ …           ┆ …      ┆ …           ┆ …                          ┆ …                │
│ PP-0021  ┆ UP-003      ┆ Diesel ┆ 1216.9      ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0022  ┆ UP-002      ┆ Gas    ┆ 611.8       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0023  ┆ UP-001      ┆ Diesel ┆ 468.1       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0024  ┆ UP-005      ┆ Coal   ┆ 1039.6      ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
│ PP-0025  ┆ UP-004      ┆ Coal   ┆ 252.6       ┆ 2026-09-04 06:22:08.670331 ┆ power_plants.csv │
└──────────┴─────────────┴────────┴─────────────┴────────────────────────────┴──────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - POWER TRANSFORMER

In [159]:
data_cleanser.clean_data(df_power_transformer, POWER_TRANSFORMER_FILE, "transformer_id", ['capacity_mva'])

shape: (1_000, 5)
┌────────────────┬───────────────┬──────────────┬────────────────────────────┬───────────────────────┐
│ transformer_id ┆ substation_id ┆ capacity_mva ┆ ingested_at                ┆ ingested_from         │
│ ---            ┆ ---           ┆ ---          ┆ ---                        ┆ ---                   │
│ str            ┆ str           ┆ f64          ┆ datetime[μs]               ┆ str                   │
╞════════════════╪═══════════════╪══════════════╪════════════════════════════╪═══════════════════════╡
│ PXF-00001      ┆ SUB-0314      ┆ 466.7        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00002      ┆ SUB-0447      ┆ 344.1        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00003      ┆ SUB-0064      ┆ 487.5        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00004      ┆ SUB-0006      ┆ 214.3        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00005      ┆ SUB-0275      ┆ 273.3        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ …              ┆ …             ┆ …            ┆ …                          ┆ …                     │
│ PXF-00996      ┆ SUB-0278      ┆ 440.2        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00997      ┆ SUB-0374      ┆ 408.1        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00998      ┆ SUB-0149      ┆ 262.8        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-00999      ┆ SUB-0437      ┆ 133.3        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
│ PXF-01000      ┆ SUB-0165      ┆ 257.9        ┆ 2026-09-04 06:24:03.094154 ┆ power_transformer.csv │
└────────────────┴───────────────┴──────────────┴────────────────────────────┴───────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - RENEWABLE SOURCE

In [161]:
data_cleanser.clean_data(df_renewable_source, RENEWABLE_SOURCE_FILE, "source_id", ['output_kw'])

shape: (40, 5)
┌───────────┬────────────┬───────────┬────────────────────────────┬──────────────────────┐
│ source_id ┆ type       ┆ output_kw ┆ ingested_at                ┆ ingested_from        │
│ ---       ┆ ---        ┆ ---       ┆ ---                        ┆ ---                  │
│ str       ┆ str        ┆ f64       ┆ datetime[μs]               ┆ str                  │
╞═══════════╪════════════╪═══════════╪════════════════════════════╪══════════════════════╡
│ RS-0001   ┆ Geothermal ┆ 10807.8   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0002   ┆ Solar      ┆ 20485.6   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0003   ┆ Geothermal ┆ 42684.8   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0004   ┆ Solar      ┆ 11773.6   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0005   ┆ Geothermal ┆ 3009.3    ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ …         ┆ …          ┆ …         ┆ …                          ┆ …                    │
│ RS-0036   ┆ Wind       ┆ 35872.8   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0037   ┆ Biomass    ┆ 22523.1   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0038   ┆ Solar      ┆ 13684.9   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0039   ┆ Wind       ┆ 4909.9    ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
│ RS-0040   ┆ Wind       ┆ 45139.9   ┆ 2026-09-04 06:26:41.564333 ┆ renewable_source.csv │
└───────────┴────────────┴───────────┴────────────────────────────┴──────────────────────┘

## -- DATA CLEANSING & HARMONIZATION   - SCADA DMS

In [164]:
data_cleanser.clean_data(df_scada_dms, SCADA_DMS_FILE, "system_id", None)

shape: (10, 6)
┌───────────┬─────────────┬───────────┬───────────────────┬────────────────────────────┬───────────────┐
│ system_id ┆ provider_id ┆ function  ┆ control_center    ┆ ingested_at                ┆ ingested_from │
│ ---       ┆ ---         ┆ ---       ┆ ---               ┆ ---                        ┆ ---           │
│ str       ┆ str         ┆ str       ┆ str               ┆ datetime[μs]               ┆ str           │
╞═══════════╪═════════════╪═══════════╪═══════════════════╪════════════════════════════╪═══════════════╡
│ SCD-001   ┆ UP-002      ┆ SCADA+DMS ┆ Control Center 1  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-002   ┆ UP-003      ┆ SCADA     ┆ Control Center 2  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-003   ┆ UP-004      ┆ SCADA+DMS ┆ Control Center 3  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-004   ┆ UP-003      ┆ SCADA     ┆ Control Center 4  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-005   ┆ UP-003      ┆ DMS       ┆ Control Center 5  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-006   ┆ UP-005      ┆ DMS       ┆ Control Center 6  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-007   ┆ UP-001      ┆ SCADA+DMS ┆ Control Center 7  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-008   ┆ UP-003      ┆ DMS       ┆ Control Center 8  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-009   ┆ UP-003      ┆ SCADA     ┆ Control Center 9  ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
│ SCD-010   ┆ UP-003      ┆ SCADA     ┆ Control Center 10 ┆ 2026-09-04 06:28:24.634216 ┆ scada_dms.csv │
└───────────┴─────────────┴───────────┴───────────────────┴────────────────────────────┴───────────────┘

## -- DATA CLEANSING & HARMONIZATION   - SMART METERS

In [166]:
data_cleanser.clean_data(df_smart_meters, SMART_METERS_FILE, "meter_id", None)

shape: (15_250_000, 9)
┌──────────────┬────────────────┬──────────────┬─────────┬──────────────┬──────────────┬───────────────┬─────────────────┬──────────────────┐
│ meter_id     ┆ transformer_id ┆ consumer_id  ┆ hes_id  ┆ install_date ┆ reading_date ┆ comm_protocol ┆ ingested_at     ┆ ingested_from    │
│ ---          ┆ ---            ┆ ---          ┆ ---     ┆ ---          ┆ ---          ┆ ---           ┆ ---             ┆ ---              │
│ str          ┆ str            ┆ str          ┆ str     ┆ str          ┆ str          ┆ str           ┆ datetime[μs]    ┆ str              │
╞══════════════╪════════════════╪══════════════╪═════════╪══════════════╪══════════════╪═══════════════╪═════════════════╪══════════════════╡
│ MTR-00000001 ┆ DXF-081750     ┆ CON-04550726 ┆ HES-026 ┆ 2019-03-12   ┆ 2026-08-08   ┆ Zigbee        ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-00000002 ┆ DXF-144459     ┆ CON-06186427 ┆ HES-061 ┆ 2015-07-30   ┆ 2026-07-17   ┆ PLC           ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-00000003 ┆ DXF-084721     ┆ CON-08057045 ┆ HES-060 ┆ 2017-05-21   ┆ 2026-08-22   ┆ Cellular      ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-00000004 ┆ DXF-022577     ┆ CON-00674983 ┆ HES-175 ┆ 2019-02-25   ┆ 2026-08-03   ┆ PLC           ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-00000005 ┆ DXF-133546     ┆ CON-01724178 ┆ HES-052 ┆ 2023-08-17   ┆ 2026-07-28   ┆ PLC           ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ …            ┆ …              ┆ …            ┆ …       ┆ …            ┆ …            ┆ …             ┆ …               ┆ …                │
│ MTR-15249996 ┆ DXF-091892     ┆ CON-07324230 ┆ HES-031 ┆ 2017-10-06   ┆ 2026-07-21   ┆ RF-Mesh       ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-15249997 ┆ DXF-045081     ┆ CON-12328533 ┆ HES-170 ┆ 2020-06-10   ┆ 2026-08-11   ┆ Zigbee        ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-15249998 ┆ DXF-014329     ┆ CON-07214584 ┆ HES-052 ┆ 2021-08-21   ┆ 2026-08-25   ┆ Zigbee        ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-15249999 ┆ DXF-097862     ┆ CON-10215735 ┆ HES-010 ┆ 2023-03-31   ┆ 2026-07-30   ┆ RF-Mesh       ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
│ MTR-15250000 ┆ DXF-136208     ┆ CON-08208856 ┆ HES-166 ┆ 2015-07-14   ┆ 2026-08-03   ┆ Zigbee        ┆ 2026-09-04      ┆ smart_meters.csv │
│              ┆                ┆              ┆         ┆              ┆              ┆               ┆ 06:29:50.432003 ┆                  │
└──────────────┴────────────────┴──────────────┴─────────┴──────────────┴──────────────┴───────────────┴─────────────────┴──────────────────┘